export const LAMBDA_SOURCE = 'LAMBDA_SOURCE';
export const LAMBDA_INPUT_REGISTER = 'LAMBDA_INPUT_REGISTER';
export const LAMBDA_INPUT = 'LAMBDA_INPUT';
export const LAMBDA_EXECUTE = 'LAMBDA_EXECUTE';
export const LAMBDA_REDUCE_REQUEST = 'LAMBDA_REDUCE_REQUEST';
export const LAMBDA_REDUCE_FAILURE = 'LAMBDA_REDUCE_FAILURE';
export const LAMBDA_REDUCE_SUCCESS = 'LAMBDA_REDUCE_SUCCESS';
export const LAMBDA_REDUCE_STEP = 'LAMBDA_REDUCE_STEP';
